const data = {
  movies: [
    {
      id: 1,
      title: "venom",
      duration: 120,
      category: "action",
      image: "./assets/images/venom.jpg",
    },
    {
      id: 2,
      title: "dunkerk",
      duration: 105,
      category: "adventure",
      image: "./assets/images/dunkerk.jpg",
    },
    {
      id: 3,
      title: "batman & superman",
      duration: 100,
      category: "thriller",
      image: "./assets/images/bat-super.jpg",
    },
    {
      id: 4,
      title: "john wick",
      duration: 120,
      category: "adventure",
      image: "./assets/images/john-wick.jpg",
    },
    {
      id: 5,
      title: "aquaman",
      duration: 130,
      category: "action",
      image: "./assets/images/aquaman.jpg",
    },
    {
      id: 6,
      title: "black panther",
      duration: 90,
      category: "thriller",
      image: "./assets/images/black-pan.jpg",
    },
    {
      id: 7,
      title: "thor",
      duration: 130,
      category: "action",
      image: "./assets/images/thor.jpg",
    },
    {
      id: 8,
      title: "bumblebee",
      duration: 100,
      category: "thriller",
      image: "./assets/images/bumblebee.png",
    },
    {
      id: 9,
      title: "mortal engines",
      duration: 100,
      category: "action",
      image: "./assets/images/mortal-engines.jpg",
    },
    {
      id: 10,
      title: "underWorld blood wars",
      duration: 100,
      category: "action",
      image: "./assets/images/underworld.jpg",
    },
  ],
  comingSoon: [
    {
      id: 1,
      title: "joney english",
      duration: 80,
      category: "comedy",
      image: "./assets/images/joneyenglish.jpg",
    },
    {
      id: 2,
      title: "WarCraft",
      duration: 120,
      category: "action",
      image: "./assets/images/warcraft.jpg",
    },
    {
      id: 3,
      title: "Rampage",
      duration: 108,
      category: "adventure",
      image: "./assets/images/rampage.jpg",
    },
    {
      id: 4,
      title: "iron lady",
      duration: 120,
      category: "comedy",
      image: "./assets/images/ironlady.jpg",
    },
    {
      id: 5,
      title: "justice league",
      duration: 120,
      category: "adventure",
      image: "./assets/images/justiceleague.jpg",
    },
    {
      id: 6,
      title: "Doctor Strange",
      duration: 120,
      category: "adventure",
      image: "./assets/images/dr-strange.jpeg",
    },
    {
      id: 7,
      title: "Captain Marvel",
      duration: 120,
      category: "adventure",
      image: "./assets/images/cap-marvel.jpg",
    },
    {
      id: 8,
      title: "Black Widow",
      duration: 90,
      category: "action",
      image: "./assets/images/black-widow.jpg",
    },
    {
      id: 9,
      title: "Ant Man",
      duration: 110,
      category: "adventure",
      image: "./assets/images/ant-man.jpg",
    },
    {
      id: 10,
      title: "Guardiance Of The Galaxy",
      duration: 120,
      category: "adventure",
      image: "./assets/images/guard-gal.jpg",
    },
  ],
};

export default data;
